window.reasonixRefreshData = {
  variants: [
    {
      id: "native",
      name: "Native Workbench",
      short: "推荐",
      accent: "graphite",
    },
    {
      id: "command",
      name: "Command Center",
      short: "命令",
      accent: "aurora",
    },
    {
      id: "studio",
      name: "Review Studio",
      short: "审查",
      accent: "ember",
    },
  ],
  tabs: [
    { id: "t1", title: "UI refresh", scope: "DeepSeek-Reasonix", mode: "plan", active: true },
    { id: "t2", title: "cache guard", scope: "internal/plugin", mode: "normal" },
    { id: "t3", title: "desktop shell", scope: "desktop/frontend", mode: "normal" },
  ],
  sessions: [
    {
      id: "s1",
      title: "重新设计桌面端 UI",
      meta: "当前 · desktop/frontend",
      active: true,
      tone: "accent",
      unread: 2,
    },
    {
      id: "s2",
      title: "review provider cache stability",
      meta: "今天 14:20",
      active: false,
      tone: "green",
      unread: 0,
    },
    {
      id: "s3",
      title: "fix workspace preview overflow",
      meta: "昨天",
      active: false,
      tone: "blue",
      unread: 0,
    },
    {
      id: "s4",
      title: "summarize MCP transport changes",
      meta: "6月7日",
      active: false,
      tone: "muted",
      unread: 0,
    },
  ],
  quickPrompts: [
    "整体审查 desktop/frontend 的 UI 层级",
    "把右侧工作区改得更像原生 inspector",
    "对比 Codex app 的标题栏和输入区",
  ],
  files: [
    { name: "desktop", type: "folder", depth: 0, open: true },
    { name: "frontend", type: "folder", depth: 1, open: true },
    { name: "src", type: "folder", depth: 2, open: true },
    { name: "App.tsx", type: "file", depth: 3, badge: "M" },
    { name: "styles.css", type: "file", depth: 3, active: true, badge: "M" },
    { name: "components", type: "folder", depth: 3, open: false },
    { name: "README.zh-CN.md", type: "file", depth: 0 },
    { name: "go.mod", type: "file", depth: 0 },
  ],
  changes: [
    { file: "desktop/frontend/src/styles.css", status: "modified", lines: "+184 -71" },
    { file: "desktop/frontend/src/components/Composer.tsx", status: "modified", lines: "+42 -18" },
    { file: "desktop/frontend/src/components/TabBar.tsx", status: "review", lines: "+21 -9" },
  ],
  commandItems: [
    { label: "New session", meta: "Open a fresh Reasonix topic", icon: "square-pen" },
    { label: "Attach current workspace", meta: "desktop/frontend", icon: "folder-git-2" },
    { label: "Show changed files", meta: "3 files touched", icon: "git-compare" },
    { label: "Switch model", meta: "mock model · browser dev", icon: "brain" },
    { label: "Open settings", meta: "Theme, language, MCP", icon: "settings" },
  ],
  initialMessages: [
    {
      id: "m1",
      role: "user",
      text: "利用 Product Design 和 baoyu-design 帮我重新设计和优化软件 UI。",
    },
    {
      id: "m2",
      role: "assistant",
      text: "我会先把整体信息架构整理成更清爽的原生桌面工作台：左侧保留会话与管理入口，中间强化任务对话，右侧作为工作区上下文和变更检查。",
      reasoning: "已读取桌面端 React/Vite 结构、主题 token、TabBar、WorkspacePanel、Transcript、Composer 和 StatusBar。",
      tools: [
        { name: "read", status: "done", meta: "desktop/frontend/src/App.tsx" },
        { name: "inspect", status: "done", meta: "docs/desktop-v2-layout-preview.png" },
        { name: "prototype", status: "running", meta: "三套 UI 方向" },
      ],
    },
  ],
  status: {
    context: "0%",
    cacheNow: "99.12%",
    cacheAvg: "91.04%",
    cost: "¥128.50",
    jobs: 1,
    balance: "¥1,428.80",
  },
};
